package main

/* All the data that goes into the partials would be here  */
import "html/template"

/* Payload object sent over when responding to the request */
type MoreInfo struct {
	ImgPath  string        // path of the image
	Header   string        // header title
	Para     template.HTML // paragraph to be shown on small devices
	LongPara template.HTML // extended definition paras for md and above devices
}

var (
	DataSplash = []MoreInfo{
		{ImgPath: "/images/tomato_gravel.png", Header: "Backyard aquaponics", Para: `<p>At Gills & Chlorophyll, we are pioneering sustainable agriculture through aquaponics, combining aquaculture and hydroponics to create a symbiotic environment where fish and plants thrive together. Our eco-friendly, efficient system uses nutrient-rich water from fish tanks to nourish plants, which
		then filter and purify the water for the fish. This closed-loop approach minimizes waste, reduces water usage, and eliminates the need for chemical fertilizers and pesticides, producing fresh, healthy food while conserving valuable resources.</p><a href="/about-aquaponics" type="button"><button type="button" class="btn btn-outline-primary btn-block">More..</button></a>`,
			LongPara: `<p> At Gills & Chlorophyll, we are pioneering the future of sustainable agriculture through the
		innovative method of aquaponics. Our unique approach harmoniously combines aquaculture and
		hydroponics, creating a symbiotic environment where fish and plants thrive together.</p><p>
		Our vision is to revolutionize farming by creating eco-friendly,efficient, and sustainable food production systems.By leveraging the natural relationship between fish and plants, we aim to produce fresh, healthy, and nutritious food while conserving
		valuable resources.</p><p>In our integrated system, nutrient-rich water from fish tanks provides essential nourishment to
		the plants. The plants, in turn, filter and purify the water, creating a clean and healthy environment for the fish. This closed-loop system minimizes waste, reduces water usage, and eliminates the need for chemical fertilizers and pesticides</p><a href="/about-aquaponics" type="button"><button type="button" class="btn btn-outline-primary">More..</button></a>`},

		{ImgPath: "/images/industrial_farming.png", Header: "Why Gills & Chlorophyll?", Para: `<p>Our method is highly sustainable, using significantly less water than traditional farming and eliminating agricultural runoff. We produce high-quality, pesticide-free vegetables and herbs, along with healthy, sustainably raised fish. By harnessing the power of nature, our innovative farming
		system is productive and efficient, adaptable to diverse environments from urban rooftops to rural
		landscapes.</p>`, LongPara: `<p><strong class="text-secondary">Sustainability:</strong> Our method reduces environmental impact
		by using significantly less water than traditional farming and eliminating agricultural runoff.</p><p><strong class="text-secondary">Quality:</strong> We produce high-quality, pesticide-free
		vegetables and herbs, along with healthy, sustainably raised fish.</p> <p><strong class="text-secondary">Innovation:</strong> By harnessing the power of nature, we create a productive and efficient farming system that can be implemented in diverse environments, from urban rooftops to rural landscapes.</p>`},

		{ImgPath: "/images/partners_farming.png", Header: "Our journey", Para: `<p>Gills & Chlorophyll is the result of a strategic joint venture between Eensymachines & Metcons, Pune. Eensymachines brings unparalleled expertise in developing cloud-connected IoT solutions, enabling advanced technological integration and remote monitoring capabilities within our aquaponics system.
		Meanwhile, Metcons Pune contributes its extensive experience in fabricating high-quality vinyls and
		robust structural components, ensuring the physical integrity and durability of our setup</p><a href="/about-journey" type="button"><button type="button" class="btn btn-outline-primary btn-block">More..</button></a>`, LongPara: `<p>Gills & Chlorophyll is the result of a strategic joint venture between Eensymachines &
		Metcons, Pune. Eensymachines brings unparalleled expertise in developing
		cloud-connected IoT solutions, enabling advanced technological integration and remote monitoring capabilities within our
		aquaponics system. Meanwhile, Metcons Pune contributes its extensive experience in fabricating
		high-quality vinyls and robust structural components, ensuring the physical integrity and durability of our
		setup.</p><p>This collaboration was a natural convergence of complementary
		skills and vision, akin to a startup poised for success. Together, we have combined cutting-edge
		technology with superior craftsmanship to create a pioneering aquaponics system that stands as a testament to
		innovation and sustainability.</p><a href="/about-journey" type="button"><button type="button" class="btn btn-outline-primary">More..</button></a>`},

		{ImgPath: "/images/joinus.png", Header: "Join us..", Para: `<p>Join us at Gills and Chlorophyll to create a greener future, where nature and technology harmonize for a sustainable food supply. Welcome to the future of farming—welcome to Gills and Chlorophyll: Harvesting Harmony.Whether you envision a setup like ours, are a dedicated environmentalist, have experience in urban farming, or have recently discovered a passion for aquaponics, we invite you to explore and contribute to our journey.</p><a href="/about-joinus" type="button"><button type="button" class="btn btn-outline-primary btn-block">More..</button></a>`, LongPara: `<p>Join us at Gills and Chlorophyll to create a greener future, where nature and technology harmonize for a sustainable food supply. Welcome to the future of farming—welcome to Gills and Chlorophyll: Harvesting Harmony.Whether you envision a setup like ours, are a dedicated environmentalist, have experience in urban farming, or have recently discovered a passion for aquaponics, we invite you to explore and contribute to our journey.</p><a href="/about-joinus" type="button"><button type="button" class="btn btn-outline-primary">More..</button></a>`},

		{ImgPath: "/images/indian_aquaponics.png", Header: "Proudly Indian", Para: `<p>At Gills and Chlorophyll, we draw from India's rich agricultural heritage and innovative spirit to advance sustainable agriculture. Our locally designed aquaponics systems utilize India's knowledge and resources, combining modern technology with eco-friendly practices to enhance food security and environmental sustainability. Proudly Indian, we are committed to nurturing our land, empowering communities, and providing fresh, nutritious food for all. Join us in paving the way for a greener, more prosperous India.</p>`, LongPara: `<p>
		At Gills and Chlorophyll, we are deeply rooted in the rich
		agricultural heritage of India.Drawing inspiration from our nation's age-old farming traditions and innovative spirit, we are committed
		to advancing sustainable agriculture for the future.</p><p>Our aquaponics systems are designed and developed locally, utilizing the wealth of knowledge and resources that India has to offer. By embracing modern technology
		and eco-friendly practices, we aim to contribute to India's food security and environmental sustainability.</p><p>
		Proudly Indian, we are dedicated to nurturing our land, empowering our communities, and providing fresh, healthy, and nutritious food for all. Join us as we pave the way for a greener and more prosperous India.</p>`},
	}
	// For the page More on aquaponics
	DataAboutAquaponics = []MoreInfo{
		{ImgPath: "/images/fishplusveggies.png", Header: "About aquaponics", Para: `<p>Aquaponics is an innovative, sustainable farming method that combines <span class="text-primary-emphasis">aquaculture (raising fish) and hydroponics (growing plants in water) to create a symbiotic, closed-loop system.</span> Nutrient-rich water from fish tanks nourishes plants, which in turn filter and purify the water, maximizing resource efficiency, reducing water usage, and eliminating the need for chemical fertilizers and pesticides. Central to this system is the natural nitrogen cycle, where fish waste is broken down by beneficial bacteria into essential nutrients for plants, fostering a balanced ecosystem. This approach promotes environmental sustainability and the production of fresh, organic food by harnessing nature's recycling mechanisms.</p>`, LongPara: `<p>
		<span class="text-primary-emphasis">Aquaponics is an innovative, sustainable farming method that combines aquaculture (raising fish) and hydroponics (growing plants in water).</span> In this symbiotic system, nutrient-rich water from the fish tanks provides essential nourishment to the plants, while the plants naturally filter and purify the water, creating a healthy environment for the fish. This <span class="text-primary-emphasis">closed-loop, soil-less system</span> maximizes resource efficiency, reduces water usage, and eliminates the need for chemical fertilizers and pesticides. Aquaponics represents a forward-thinking approach to agriculture, <span class="text-primary-emphasis">promoting environmental sustainability and the production of fresh, organic food.</span>
	</p><p>
		At the heart of our aquaponics system lies the efficient and sustainable use of nature's <span class="text-primary-emphasis">nitrogen cycle.</span> This natural process creates a harmonious recycling mechanism where fish in the tanks produce waste, which is then broken down by beneficial bacteria into essential nutrients for the plants. The plants, in turn, absorb these nutrients, effectively purifying the water before it circulates back to the fish tanks. This <span class="text-primary-emphasis">symbiotic relationship</span> not only fosters a balanced ecosystem but also maximizes resource efficiency by minimizing waste and reducing the need for external inputs such as chemical fertilizers. Through this innovative approach, we harness the power of nature to cultivate healthy, organic produce and sustainably raised fish, contributing to a more sustainable and <span class="text-primary-emphasis">environmentally friendly food production system.</span>
	</p>`},
		{ImgPath: "/images/cloud_connected.png", Header: "Technological integrations", Para: `<p>
		At Gills and Chlorophyll, we enhance our aquaponics system's efficiency and sustainability by integrating advanced technology. Our <span class="text-primary-emphasis">cloud-connected, remotely programmable pump allows precise control of water and nutrient flow, enabling real-time monitoring and adjustments for optimal performance.</span> This technology provides unparalleled flexibility and control, ensuring a balanced, thriving environment. Additionally, to reduce our carbon footprint and electricity costs, we installed a solar panel to power the entire setup, making our system more sustainable and future-proof.</p>`, LongPara: ` <p>
		At Gills and Chlorophyll, we have taken a significant step forward by integrating advanced technology into our aquaponics system, enhancing both its efficiency and sustainability. Recognizing the pivotal role of the pump, which serves as the heart of our system, we have made it <span class="text-primary-emphasis">cloud-connected and remotely programmable.</span> This innovative approach allows us to precisely control the pump's operation, optimizing the flow of water and nutrients to the plants. Our <span class="text-primary-emphasis">cloud-based system enables real-time monitoring and adjustments, ensuring optimal performance at all times.</span> Additionally, the pump's settings can be conveniently reprogrammed from handheld devices, providing us with unparalleled flexibility and control. This seamless integration of technology not only improves the overall functionality of our aquaponics system but also ensures that we can maintain the delicate balance required for a thriving, symbiotic environment.
	</p>`},
		{ImgPath: "/images/sustainable_solutions.png", Header: "Sustainable energy solutions", Para: `<p>
		Energizing our cloud-connected system and powering the A/C pump initially required significant electricity, adding to our carbon footprint. To enhance sustainability, we installed a <span class="text-primary-emphasis">solar panel array that now powers the entire setup.</span> By utilizing solar energy, we've reduced reliance on conventional sources, lowered utility bills, and made our system more resilient and future-proof. <span class="text-primary-emphasis">This shift underscores our commitment to environmental stewardship and sustainable agriculture, ensuring Gills and Chlorophyll stays at the forefront of eco-friendly innovation.</span></p>`, LongPara: `<p>
		Energizing our cloud-connected system and powering the A/C pump traditionally required a significant amount of electricity, contributing to the overall carbon footprint of the operation. To address this challenge and enhance the sustainability of our aquaponics system, we installed a <span class="text-primary-emphasis">solar panel array that now drives the entire setup.</span> By harnessing the power of the sun, we have significantly reduced our reliance on conventional energy sources. This shift to renewable energy has not only <span class="text-primary-emphasis">lowered our monthly utility bills but has also made our system more resilient and future-proof.</span> Embracing such unconventional energy resources underscores our commitment to environmental stewardship and sustainable agriculture, ensuring that Gills and Chlorophyll remains at the forefront of eco-friendly innovation.
	</p>`},
	}
	DataAboutJourney = []MoreInfo{
		{ImgPath: "/images/agriculture.png", Header: "Our journey", Para: `<p>We began our journey as two engineers from the Maharashtra Institute of Technology, Pune. With two decades of diverse professional experiences—one in corporate IT and the other managing a family business—we started prototyping a cloud-connected urban farm, inspired by our children's passion for gardening. In March 2024, we built our first prototype, using knowledge from YouTube courses and "Aquaponic Gardening" by Sylvia Bernstein. The setup featured tomato plants, powered entirely by solar energy, with an automated water pump. By June 2024, we harvested a dozen tomatoes. The ornamental fish in our system have bred successfully, and despite some losses, most are thriving. We plan to add jalapeños and eventually avocados to our setup.</p>`, LongPara: `<p>We began our journey as two modest engineers from the Maharashtra Institute of Technology,Pune. After two decades of diverse professional experiences—one in corporate IT and the other managing a successful family business—we embarked on prototyping a cloud-connected urban farm. Inspired by our children's enthusiasm for gardening and growing their own food, we recognized the unique passion of Generation Alpha for returning to their roots and fostering sustainable practices. It's truly heartening to see them embrace the art of growing their own food.</p> <p>In March 2024, we meticulously constructed our first prototype, drawing from our extensive knowledge gained through numerous YouTube courses and the book "Aquaponic Gardening" by Sylvia Bernstein. Our setup featured half a dozen tomato plants and was entirely powered by solar energy. We automated the water pump to synchronize with the flood and drain cycle. By June 2024, we successfully harvested about a dozen tomatoes. Although the fish in our system are primarily ornamental, they have bred new fry, and aside from a few losses during experimentation, we have managed to keep most of them thriving and content.</p><p>As I write this up we have also plans to add jalapenos alongside the tomatoes. Avacados are tricky but someday yes! we would also want to add avocados to the setup as well.</p>`},

		{ImgPath: "/images/niranjan.jpg", Header: "Niranjan Awati", Para: `<p>Niranjan Awati, a mechanical engineering graduate from the Maharashtra Institute of Technology, Pune, transitioned to the Internet of Things (IoT) early in his career at Infosys. Over two decades, he has developed numerous automation systems, working with organizations like Infosys, Dheeti Technologies, NCS-i, and Persistent Systems. Though aquaponics was always a passion, he never anticipated pursuing it seriously or on such a large scale. His daughter, Yakshita, turning three in October 2024, is already an enthusiastic gardener, actively participating in their balcony garden from planting seeds to watering plants.</p>`, LongPara: `<p>Niranjan Awati is a mechanical engineering graduate from the Maharashtra Institute of Technology, Pune. He transitioned to the Internet of Things (IoT) early in his career at Infosys. Over the course of two decades, he has developed and designed numerous automation systems, working with esteemed organizations such as Infosys, Dheeti Technologies, NCS-i, and Persistent Systems.</p><p>While aquaponics has always been a passion for Niranjan, he never anticipated pursuing it seriously or undertaking such a large-scale project. His daughter, Yakshita, who will turn three in October 2024, is already an enthusiastic gardener. She keenly participates in all aspects of their balcony garden, from planting seeds to watering the plants.</p>`},

		{ImgPath: "/images/tejas.jpg", Header: "Tejas Cholkar", Para: `<p>Tejas, a mechanical engineering graduate from the Maharashtra Institute of Technology, Pune, has managed two thriving medium-sized manufacturing plants for over 20 years. Leveraging his postgraduate degree in business management, he successfully took over his family business and established an additional unit. An avid gardener and dedicated fish keeper, Tejas's passion is shared by his son, Nirav, who will turn ten this September and enthusiastically manages most of the gardening and fish-keeping tasks at home.</p>`, LongPara: `<p>Tejas is also a mechanical engineering graduate from the Maharashtra Institute of Technology, Pune. For over 20 years, he has successfully managed two thriving medium-sized manufacturing plants. Leveraging his business acumen gained from a postgraduate degree in business management, Tejas not only succeeded his father in managing the family business but also established an additional unit.</p><p>In addition to his professional achievements, Tejas is an avid gardener and dedicated fish keeper. His son, Nirav, who will turn ten this September, enthusiastically handles most of the gardening and fish keeping tasks at home.</p>`},
	}
	DataAboutJoinus = []MoreInfo{
		{ImgPath: "/images/harevst_small.png", Header: "How can you join us?", Para: `<p>Have you always envisioned creating a setup like ours? Are you a dedicated environmentalist? Perhaps you have a background in urban farming and are keen to explore further. Or maybe you are a visitor to our website who has recently discovered a newfound passion for aquaponics.</p>`, LongPara: `<p>Have you always envisioned creating a setup like ours? Are you a dedicated environmentalist? Perhaps you have a background in urban farming and are keen to explore further. Or maybe you are a visitor to our website who has recently discovered a newfound passion for aquaponics.</p>`},

		{ImgPath: "/images/vegetable_garden.png", Header: "You are welcome", Para: `<p>We began this journey as a hobby with limited resources, facing challenges that included the loss of fish and plants. These early setbacks were invaluable learning experiences that shaped our current expertise. We are not disheartened but see these difficulties as essential for our growth. If you have insights or experience in urban farming and are willing to contribute, we would greatly value your knowledge and passion to enhance our aquaponics efforts.</p>`, LongPara: `<p>We embarked on this journey as a hobby, utilizing the limited resources we had at our disposal. Our initial trials were fraught with challenges; we experienced the loss of half a dozen fish and several plants. These early setbacks, however, were invaluable learning experiences that have shaped our current knowledge and expertise.</p><p>We are not disheartened by these difficulties. Instead, we recognize that they were essential in our growth and development. If you possess any insights or experience in urban farming and are willing to contribute, you are precisely the kind of person we are looking for. Your knowledge and passion could greatly enhance our efforts and help us achieve even greater success in our aquaponics endeavors.</p>`},

		{ImgPath: "/images/print_style.png", Header: "What could you help us with?", Para: `<p>If you're a passive investor looking to join the future wave of urban farming, book an early seat now. Experienced farmer who wants to contribute your expertise? Come help us; second chances often bring the most glory. Technological expert in cloud solutions, sensors, or PCB design? Apply your skills to farming with us. Environmental expert focused on reducing carbon footprints? Your ideas are welcome. Please write to us at [email address] or DM us on LinkedIn. Ideally, you are in Pune to visit the site frequently, but we are happy to connect virtually if not.</p>`, LongPara: `<ul><li>Business capital - If you are one of those passive investors who is looking to ride the future wave of urban farming, book an early seat ! Here is your chance.</li><li>Domain expertise - You have already been a farmer before, but somehow could not sustain (or perhaps are doing way better than us) - hence find this invigorating, come help us - life does indeed give second chances. - often the most glorious ones.</li><li>Technological expertise - Cloud , cloud connected solutions, sensors, electronics PCB design is your forte. Always wanted to apply that on farming ? Yep you are the one we are looking for.</li><li>Environmental expert - If you have seen our profiles, you'd notice none of us is an core environmentalists. But if you are the one who does Carbon footprint calculations, and have more ideas for us you are utmost welcome.</li></ul><p>Please write to us at [email address] or DM us here on LinkedIn if you feel you can team up. Im hoping you are also in Pune as to visit the site frequently. But incase you are not we are still happy to play tag-team - just that in such case we would have to make arrangements to connect virtually.</p>`},
	}
)
